# Generated by Django 4.0.3 on 2022-05-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('task_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_taker', to=settings.AUTH_USER_MODEL)),
                ('task_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
